// Mocks generated by Mockito 5.4.6 from annotations
// in croiz/test/widget/cyrillic_keyboard_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:croiz/features/statistics/models/puzzle_stat.dart' as _i5;
import 'package:croiz/features/statistics/models/user_stats.dart' as _i2;
import 'package:croiz/features/statistics/services/statistics_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserStats_0 extends _i1.SmartFake implements _i2.UserStats {
  _FakeUserStats_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StatisticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatisticsService extends _i1.Mock implements _i3.StatisticsService {
  @override
  _i4.Future<_i2.UserStats> getOrInitUserStats() =>
      (super.noSuchMethod(
            Invocation.method(#getOrInitUserStats, []),
            returnValue: _i4.Future<_i2.UserStats>.value(
              _FakeUserStats_0(
                this,
                Invocation.method(#getOrInitUserStats, []),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.UserStats>.value(
              _FakeUserStats_0(
                this,
                Invocation.method(#getOrInitUserStats, []),
              ),
            ),
          )
          as _i4.Future<_i2.UserStats>);

  @override
  _i4.Future<void> recordPuzzleCompletion({
    required String? puzzleId,
    required int? timeSeconds,
    required int? totalWords,
    required int? wordsFound,
    required int? hintsUsed,
    required double? accuracy,
    required int? wordsRevealed,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordPuzzleCompletion, [], {
              #puzzleId: puzzleId,
              #timeSeconds: timeSeconds,
              #totalWords: totalWords,
              #wordsFound: wordsFound,
              #hintsUsed: hintsUsed,
              #accuracy: accuracy,
              #wordsRevealed: wordsRevealed,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i5.PuzzleStat>> watchRecentCompletions({int? limit = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#watchRecentCompletions, [], {#limit: limit}),
            returnValue: _i4.Stream<List<_i5.PuzzleStat>>.empty(),
            returnValueForMissingStub: _i4.Stream<List<_i5.PuzzleStat>>.empty(),
          )
          as _i4.Stream<List<_i5.PuzzleStat>>);

  @override
  _i4.Future<List<_i5.PuzzleStat>> getAllCompletions() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCompletions, []),
            returnValue: _i4.Future<List<_i5.PuzzleStat>>.value(
              <_i5.PuzzleStat>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i5.PuzzleStat>>.value(
              <_i5.PuzzleStat>[],
            ),
          )
          as _i4.Future<List<_i5.PuzzleStat>>);
}
