// Mocks generated by Mockito 5.4.6 from annotations
// in croiz/test/widget/puzzle_generation_notification_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;
import 'dart:ui' as _i14;

import 'package:flutter/foundation.dart' as _i10;
import 'package:flutter/services.dart' as _i15;
import 'package:flutter/widgets.dart' as _i4;
import 'package:go_router/src/builder.dart' as _i8;
import 'package:go_router/src/configuration.dart' as _i3;
import 'package:go_router/src/delegate.dart' as _i5;
import 'package:go_router/src/information_provider.dart' as _i6;
import 'package:go_router/src/match.dart' as _i9;
import 'package:go_router/src/parser.dart' as _i7;
import 'package:go_router/src/router.dart' as _i11;
import 'package:go_router/src/state.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGoRouterState_0 extends _i1.SmartFake implements _i2.GoRouterState {
  _FakeGoRouterState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteConfiguration_1 extends _i1.SmartFake
    implements _i3.RouteConfiguration {
  _FakeRouteConfiguration_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBackButtonDispatcher_2 extends _i1.SmartFake
    implements _i4.BackButtonDispatcher {
  _FakeBackButtonDispatcher_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoRouterDelegate_3 extends _i1.SmartFake
    implements _i5.GoRouterDelegate {
  _FakeGoRouterDelegate_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoRouteInformationProvider_4 extends _i1.SmartFake
    implements _i6.GoRouteInformationProvider {
  _FakeGoRouteInformationProvider_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoRouteInformationParser_5 extends _i1.SmartFake
    implements _i7.GoRouteInformationParser {
  _FakeGoRouteInformationParser_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteBuilder_6 extends _i1.SmartFake implements _i8.RouteBuilder {
  _FakeRouteBuilder_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGlobalKey_7<T extends _i4.State<_i4.StatefulWidget>>
    extends _i1.SmartFake
    implements _i4.GlobalKey<T> {
  _FakeGlobalKey_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteMatchList_8 extends _i1.SmartFake
    implements _i9.RouteMatchList {
  _FakeRouteMatchList_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({
    _i10.DiagnosticLevel? minLevel = _i10.DiagnosticLevel.info,
  }) => super.toString();
}

class _FakeWidget_9 extends _i1.SmartFake implements _i4.Widget {
  _FakeWidget_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({
    _i10.DiagnosticLevel? minLevel = _i10.DiagnosticLevel.info,
  }) => super.toString();
}

class _FakeGoRouter_10 extends _i1.SmartFake implements _i11.GoRouter {
  _FakeGoRouter_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteInformation_11 extends _i1.SmartFake
    implements _i4.RouteInformation {
  _FakeRouteInformation_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GoRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoRouter extends _i1.Mock implements _i11.GoRouter {
  @override
  _i2.GoRouterState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeGoRouterState_0(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeGoRouterState_0(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.GoRouterState);

  @override
  _i3.RouteConfiguration get configuration =>
      (super.noSuchMethod(
            Invocation.getter(#configuration),
            returnValue: _FakeRouteConfiguration_1(
              this,
              Invocation.getter(#configuration),
            ),
            returnValueForMissingStub: _FakeRouteConfiguration_1(
              this,
              Invocation.getter(#configuration),
            ),
          )
          as _i3.RouteConfiguration);

  @override
  _i4.BackButtonDispatcher get backButtonDispatcher =>
      (super.noSuchMethod(
            Invocation.getter(#backButtonDispatcher),
            returnValue: _FakeBackButtonDispatcher_2(
              this,
              Invocation.getter(#backButtonDispatcher),
            ),
            returnValueForMissingStub: _FakeBackButtonDispatcher_2(
              this,
              Invocation.getter(#backButtonDispatcher),
            ),
          )
          as _i4.BackButtonDispatcher);

  @override
  _i5.GoRouterDelegate get routerDelegate =>
      (super.noSuchMethod(
            Invocation.getter(#routerDelegate),
            returnValue: _FakeGoRouterDelegate_3(
              this,
              Invocation.getter(#routerDelegate),
            ),
            returnValueForMissingStub: _FakeGoRouterDelegate_3(
              this,
              Invocation.getter(#routerDelegate),
            ),
          )
          as _i5.GoRouterDelegate);

  @override
  _i6.GoRouteInformationProvider get routeInformationProvider =>
      (super.noSuchMethod(
            Invocation.getter(#routeInformationProvider),
            returnValue: _FakeGoRouteInformationProvider_4(
              this,
              Invocation.getter(#routeInformationProvider),
            ),
            returnValueForMissingStub: _FakeGoRouteInformationProvider_4(
              this,
              Invocation.getter(#routeInformationProvider),
            ),
          )
          as _i6.GoRouteInformationProvider);

  @override
  _i7.GoRouteInformationParser get routeInformationParser =>
      (super.noSuchMethod(
            Invocation.getter(#routeInformationParser),
            returnValue: _FakeGoRouteInformationParser_5(
              this,
              Invocation.getter(#routeInformationParser),
            ),
            returnValueForMissingStub: _FakeGoRouteInformationParser_5(
              this,
              Invocation.getter(#routeInformationParser),
            ),
          )
          as _i7.GoRouteInformationParser);

  @override
  bool get overridePlatformDefaultLocation =>
      (super.noSuchMethod(
            Invocation.getter(#overridePlatformDefaultLocation),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set configuration(_i3.RouteConfiguration? value) => super.noSuchMethod(
    Invocation.setter(#configuration, value),
    returnValueForMissingStub: null,
  );

  @override
  set routerDelegate(_i5.GoRouterDelegate? value) => super.noSuchMethod(
    Invocation.setter(#routerDelegate, value),
    returnValueForMissingStub: null,
  );

  @override
  set routeInformationProvider(_i6.GoRouteInformationProvider? value) =>
      super.noSuchMethod(
        Invocation.setter(#routeInformationProvider, value),
        returnValueForMissingStub: null,
      );

  @override
  set routeInformationParser(_i7.GoRouteInformationParser? value) =>
      super.noSuchMethod(
        Invocation.setter(#routeInformationParser, value),
        returnValueForMissingStub: null,
      );

  @override
  bool canPop() =>
      (super.noSuchMethod(
            Invocation.method(#canPop, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String namedLocation(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    String? fragment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #namedLocation,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #fragment: fragment,
              },
            ),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(
                #namedLocation,
                [name],
                {
                  #pathParameters: pathParameters,
                  #queryParameters: queryParameters,
                  #fragment: fragment,
                },
              ),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.method(
                #namedLocation,
                [name],
                {
                  #pathParameters: pathParameters,
                  #queryParameters: queryParameters,
                  #fragment: fragment,
                },
              ),
            ),
          )
          as String);

  @override
  void go(String? location, {Object? extra}) => super.noSuchMethod(
    Invocation.method(#go, [location], {#extra: extra}),
    returnValueForMissingStub: null,
  );

  @override
  void restore(_i9.RouteMatchList? matchList) => super.noSuchMethod(
    Invocation.method(#restore, [matchList]),
    returnValueForMissingStub: null,
  );

  @override
  void goNamed(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
    String? fragment,
  }) => super.noSuchMethod(
    Invocation.method(
      #goNamed,
      [name],
      {
        #pathParameters: pathParameters,
        #queryParameters: queryParameters,
        #extra: extra,
        #fragment: fragment,
      },
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<T?> push<T extends Object?>(String? location, {Object? extra}) =>
      (super.noSuchMethod(
            Invocation.method(#push, [location], {#extra: extra}),
            returnValue: _i13.Future<T?>.value(),
            returnValueForMissingStub: _i13.Future<T?>.value(),
          )
          as _i13.Future<T?>);

  @override
  _i13.Future<T?> pushNamed<T extends Object?>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushNamed,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #extra: extra,
              },
            ),
            returnValue: _i13.Future<T?>.value(),
            returnValueForMissingStub: _i13.Future<T?>.value(),
          )
          as _i13.Future<T?>);

  @override
  _i13.Future<T?> pushReplacement<T extends Object?>(
    String? location, {
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pushReplacement, [location], {#extra: extra}),
            returnValue: _i13.Future<T?>.value(),
            returnValueForMissingStub: _i13.Future<T?>.value(),
          )
          as _i13.Future<T?>);

  @override
  _i13.Future<T?> pushReplacementNamed<T extends Object?>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushReplacementNamed,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #extra: extra,
              },
            ),
            returnValue: _i13.Future<T?>.value(),
            returnValueForMissingStub: _i13.Future<T?>.value(),
          )
          as _i13.Future<T?>);

  @override
  _i13.Future<T?> replace<T>(String? location, {Object? extra}) =>
      (super.noSuchMethod(
            Invocation.method(#replace, [location], {#extra: extra}),
            returnValue: _i13.Future<T?>.value(),
            returnValueForMissingStub: _i13.Future<T?>.value(),
          )
          as _i13.Future<T?>);

  @override
  _i13.Future<T?> replaceNamed<T>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #replaceNamed,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #extra: extra,
              },
            ),
            returnValue: _i13.Future<T?>.value(),
            returnValueForMissingStub: _i13.Future<T?>.value(),
          )
          as _i13.Future<T?>);

  @override
  void pop<T extends Object?>([T? result]) => super.noSuchMethod(
    Invocation.method(#pop, [result]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GoRouterDelegate].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoRouterDelegate extends _i1.Mock implements _i5.GoRouterDelegate {
  @override
  _i8.RouteBuilder get builder =>
      (super.noSuchMethod(
            Invocation.getter(#builder),
            returnValue: _FakeRouteBuilder_6(this, Invocation.getter(#builder)),
            returnValueForMissingStub: _FakeRouteBuilder_6(
              this,
              Invocation.getter(#builder),
            ),
          )
          as _i8.RouteBuilder);

  @override
  bool get routerNeglect =>
      (super.noSuchMethod(
            Invocation.getter(#routerNeglect),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.GoRouterState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeGoRouterState_0(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeGoRouterState_0(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.GoRouterState);

  @override
  _i4.GlobalKey<_i4.NavigatorState> get navigatorKey =>
      (super.noSuchMethod(
            Invocation.getter(#navigatorKey),
            returnValue: _FakeGlobalKey_7<_i4.NavigatorState>(
              this,
              Invocation.getter(#navigatorKey),
            ),
            returnValueForMissingStub: _FakeGlobalKey_7<_i4.NavigatorState>(
              this,
              Invocation.getter(#navigatorKey),
            ),
          )
          as _i4.GlobalKey<_i4.NavigatorState>);

  @override
  _i9.RouteMatchList get currentConfiguration =>
      (super.noSuchMethod(
            Invocation.getter(#currentConfiguration),
            returnValue: _FakeRouteMatchList_8(
              this,
              Invocation.getter(#currentConfiguration),
            ),
            returnValueForMissingStub: _FakeRouteMatchList_8(
              this,
              Invocation.getter(#currentConfiguration),
            ),
          )
          as _i9.RouteMatchList);

  @override
  set builder(_i8.RouteBuilder? value) => super.noSuchMethod(
    Invocation.setter(#builder, value),
    returnValueForMissingStub: null,
  );

  @override
  set currentConfiguration(_i9.RouteMatchList? value) => super.noSuchMethod(
    Invocation.setter(#currentConfiguration, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i13.Future<bool> popRoute() =>
      (super.noSuchMethod(
            Invocation.method(#popRoute, []),
            returnValue: _i13.Future<bool>.value(false),
            returnValueForMissingStub: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  bool canPop() =>
      (super.noSuchMethod(
            Invocation.method(#canPop, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void pop<T extends Object?>([T? result]) => super.noSuchMethod(
    Invocation.method(#pop, [result]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Widget build(_i4.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#build, [context]),
            returnValue: _FakeWidget_9(
              this,
              Invocation.method(#build, [context]),
            ),
            returnValueForMissingStub: _FakeWidget_9(
              this,
              Invocation.method(#build, [context]),
            ),
          )
          as _i4.Widget);

  @override
  _i13.Future<void> setNewRoutePath(_i9.RouteMatchList? configuration) =>
      (super.noSuchMethod(
            Invocation.method(#setNewRoutePath, [configuration]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> setInitialRoutePath(_i9.RouteMatchList? configuration) =>
      (super.noSuchMethod(
            Invocation.method(#setInitialRoutePath, [configuration]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> setRestoredRoutePath(_i9.RouteMatchList? configuration) =>
      (super.noSuchMethod(
            Invocation.method(#setRestoredRoutePath, [configuration]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GoRouteInformationParser].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoRouteInformationParser extends _i1.Mock
    implements _i7.GoRouteInformationParser {
  @override
  _i3.RouteConfiguration get configuration =>
      (super.noSuchMethod(
            Invocation.getter(#configuration),
            returnValue: _FakeRouteConfiguration_1(
              this,
              Invocation.getter(#configuration),
            ),
            returnValueForMissingStub: _FakeRouteConfiguration_1(
              this,
              Invocation.getter(#configuration),
            ),
          )
          as _i3.RouteConfiguration);

  @override
  _i11.GoRouter get router =>
      (super.noSuchMethod(
            Invocation.getter(#router),
            returnValue: _FakeGoRouter_10(this, Invocation.getter(#router)),
            returnValueForMissingStub: _FakeGoRouter_10(
              this,
              Invocation.getter(#router),
            ),
          )
          as _i11.GoRouter);

  @override
  set debugParserFuture(_i13.Future<_i9.RouteMatchList>? value) =>
      super.noSuchMethod(
        Invocation.setter(#debugParserFuture, value),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<_i9.RouteMatchList> parseRouteInformationWithDependencies(
    _i4.RouteInformation? routeInformation,
    _i4.BuildContext? context,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#parseRouteInformationWithDependencies, [
              routeInformation,
              context,
            ]),
            returnValue: _i13.Future<_i9.RouteMatchList>.value(
              _FakeRouteMatchList_8(
                this,
                Invocation.method(#parseRouteInformationWithDependencies, [
                  routeInformation,
                  context,
                ]),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i9.RouteMatchList>.value(
              _FakeRouteMatchList_8(
                this,
                Invocation.method(#parseRouteInformationWithDependencies, [
                  routeInformation,
                  context,
                ]),
              ),
            ),
          )
          as _i13.Future<_i9.RouteMatchList>);

  @override
  _i13.Future<_i9.RouteMatchList> parseRouteInformation(
    _i4.RouteInformation? routeInformation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#parseRouteInformation, [routeInformation]),
            returnValue: _i13.Future<_i9.RouteMatchList>.value(
              _FakeRouteMatchList_8(
                this,
                Invocation.method(#parseRouteInformation, [routeInformation]),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i9.RouteMatchList>.value(
              _FakeRouteMatchList_8(
                this,
                Invocation.method(#parseRouteInformation, [routeInformation]),
              ),
            ),
          )
          as _i13.Future<_i9.RouteMatchList>);

  @override
  _i4.RouteInformation? restoreRouteInformation(
    _i9.RouteMatchList? configuration,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#restoreRouteInformation, [configuration]),
            returnValueForMissingStub: null,
          )
          as _i4.RouteInformation?);
}

/// A class which mocks [GoRouteInformationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoRouteInformationProvider extends _i1.Mock
    implements _i6.GoRouteInformationProvider {
  @override
  _i4.RouteInformation get value =>
      (super.noSuchMethod(
            Invocation.getter(#value),
            returnValue: _FakeRouteInformation_11(
              this,
              Invocation.getter(#value),
            ),
            returnValueForMissingStub: _FakeRouteInformation_11(
              this,
              Invocation.getter(#value),
            ),
          )
          as _i4.RouteInformation);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void routerReportsNewRouteInformation(
    _i4.RouteInformation? routeInformation, {
    _i4.RouteInformationReportingType? type =
        _i4.RouteInformationReportingType.none,
  }) => super.noSuchMethod(
    Invocation.method(
      #routerReportsNewRouteInformation,
      [routeInformation],
      {#type: type},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<T?> push<T>(
    String? location, {
    required _i9.RouteMatchList? base,
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#push, [location], {#base: base, #extra: extra}),
            returnValue: _i13.Future<T?>.value(),
            returnValueForMissingStub: _i13.Future<T?>.value(),
          )
          as _i13.Future<T?>);

  @override
  void go(String? location, {Object? extra}) => super.noSuchMethod(
    Invocation.method(#go, [location], {#extra: extra}),
    returnValueForMissingStub: null,
  );

  @override
  void restore(String? location, {required _i9.RouteMatchList? matchList}) =>
      super.noSuchMethod(
        Invocation.method(#restore, [location], {#matchList: matchList}),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<T?> pushReplacement<T>(
    String? location, {
    required _i9.RouteMatchList? base,
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushReplacement,
              [location],
              {#base: base, #extra: extra},
            ),
            returnValue: _i13.Future<T?>.value(),
            returnValueForMissingStub: _i13.Future<T?>.value(),
          )
          as _i13.Future<T?>);

  @override
  _i13.Future<T?> replace<T>(
    String? location, {
    required _i9.RouteMatchList? base,
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #replace,
              [location],
              {#base: base, #extra: extra},
            ),
            returnValue: _i13.Future<T?>.value(),
            returnValueForMissingStub: _i13.Future<T?>.value(),
          )
          as _i13.Future<T?>);

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<bool> didPushRouteInformation(
    _i4.RouteInformation? routeInformation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#didPushRouteInformation, [routeInformation]),
            returnValue: _i13.Future<bool>.value(false),
            returnValueForMissingStub: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<bool> didPopRoute() =>
      (super.noSuchMethod(
            Invocation.method(#didPopRoute, []),
            returnValue: _i13.Future<bool>.value(false),
            returnValueForMissingStub: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  bool handleStartBackGesture(_i15.PredictiveBackEvent? backEvent) =>
      (super.noSuchMethod(
            Invocation.method(#handleStartBackGesture, [backEvent]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void handleUpdateBackGestureProgress(_i15.PredictiveBackEvent? backEvent) =>
      super.noSuchMethod(
        Invocation.method(#handleUpdateBackGestureProgress, [backEvent]),
        returnValueForMissingStub: null,
      );

  @override
  void handleCommitBackGesture() => super.noSuchMethod(
    Invocation.method(#handleCommitBackGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  void handleCancelBackGesture() => super.noSuchMethod(
    Invocation.method(#handleCancelBackGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<bool> didPushRoute(String? route) =>
      (super.noSuchMethod(
            Invocation.method(#didPushRoute, [route]),
            returnValue: _i13.Future<bool>.value(false),
            returnValueForMissingStub: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  void didChangeMetrics() => super.noSuchMethod(
    Invocation.method(#didChangeMetrics, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTextScaleFactor() => super.noSuchMethod(
    Invocation.method(#didChangeTextScaleFactor, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangePlatformBrightness() => super.noSuchMethod(
    Invocation.method(#didChangePlatformBrightness, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeLocales(List<_i14.Locale>? locales) => super.noSuchMethod(
    Invocation.method(#didChangeLocales, [locales]),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeAppLifecycleState(_i14.AppLifecycleState? state) =>
      super.noSuchMethod(
        Invocation.method(#didChangeAppLifecycleState, [state]),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeViewFocus(_i14.ViewFocusEvent? event) => super.noSuchMethod(
    Invocation.method(#didChangeViewFocus, [event]),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<_i14.AppExitResponse> didRequestAppExit() =>
      (super.noSuchMethod(
            Invocation.method(#didRequestAppExit, []),
            returnValue: _i13.Future<_i14.AppExitResponse>.value(
              _i14.AppExitResponse.exit,
            ),
            returnValueForMissingStub: _i13.Future<_i14.AppExitResponse>.value(
              _i14.AppExitResponse.exit,
            ),
          )
          as _i13.Future<_i14.AppExitResponse>);

  @override
  void didHaveMemoryPressure() => super.noSuchMethod(
    Invocation.method(#didHaveMemoryPressure, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeAccessibilityFeatures() => super.noSuchMethod(
    Invocation.method(#didChangeAccessibilityFeatures, []),
    returnValueForMissingStub: null,
  );
}
