import 'dart:developer' as developer;
import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

import 'package:croiz/domain/entities/game_entities.dart';
import 'package:croiz/features/game/helpers/board_helpers.dart';
import 'package:croiz/features/game/services/incorrect_letter_cleaner.dart';
import 'package:croiz/services/providers.dart';
import 'package:croiz/features/game/services/game_persistence_service.dart';
import 'package:croiz/features/game/services/game_progress_service.dart';
import 'package:croiz/features/game/services/game_reveal_service.dart';
import 'package:croiz/features/game/services/game_endgame_service.dart';

import 'puzzle_loader_provider.dart';
import 'game_state_providers.dart';
import 'game_timer_provider.dart';

part 'game_board_notifier.g.dart';

/// Duration used to schedule clearing of flashed cells after animations.
/// Tests can override this provider to `Duration.zero` to avoid scheduling
/// real timers (FakeAsync-friendly).
@Riverpod(keepAlive: true)
Duration flashClearDelay(Ref ref) => const Duration(milliseconds: 300);

// Compatibility alias removed: flashClearDelayProvider is generated by riverpod_generator

/// Debounce delay for word completion checks during fast typing.
/// In production: 16ms (one frame) to batch checks while staying responsive.
/// Tests can override to Duration.zero for synchronous checks.
@Riverpod(keepAlive: true)
Duration wordCheckDebounceDelay(Ref ref) => const Duration(milliseconds: 16);

// Compatibility alias removed: wordCheckDebounceDelayProvider is generated by riverpod_generator

/// Main notifier for the game board state.
@Riverpod(
  keepAlive: true,
  dependencies: [
    puzzleLoader,
    gamePersistenceService,
    gameProgressService,
    gameRevealService,
    gameEndgameService,
    SelectedPuzzleIdNotifier,
    SelectedCellNotifier,
    FoundWordsNotifier,
    LockedCellsNotifier,
    FlashingCellsNotifier,
    FlashingClearedCellsNotifier,
    flashClearDelay,
    gameTimer,
    AudioMutedNotifier,
    gameAudioService,
  ],
)
class GameBoardNotifier extends _$GameBoardNotifier {
  // Track the last loaded puzzle ID to detect changes
  String? _lastLoadedPuzzleId;
  // Track the previous board's grid for persistence on puzzle switch
  List<List<String?>>? _previousGrid;
  // Track the last restored puzzle ID to avoid infinite loops
  String? _lastRestoredId;

  // Use the service via provider if available, otherwise fallback to local instance
  late final GamePersistenceService _persistenceService = ref.watch(
    gamePersistenceServiceProvider,
  );
  late final GameProgressService _progressService = ref.watch(
    gameProgressServiceProvider,
  );
  late final GameRevealService _revealService = ref.watch(
    gameRevealServiceProvider,
  );
  late final GameEndgameService _endgameService = ref.watch(
    gameEndgameServiceProvider,
  );

  // Compatibility helper used by tests and legacy call sites.
  void setBoard(GameBoard board) => state = board;

  @override
  GameBoard build() {
    // Listen for changes to puzzleLoaderProvider to restore progress.
    // Note: Riverpod manages the subscription lifecycle - we don't need
    // to track _listenerAttached because ref.listen is designed to be
    // called in build() and is automatically cleaned up on rebuild.
    ref
      ..listen<AsyncValue<GameBoard>>(
        puzzleLoaderProvider,
        _onPuzzleLoaderChanged,
        fireImmediately:
            true, // Fire immediately to handle initial load/restore
      )
      // Cancel any pending timers when the notifier is disposed by Riverpod.
      ..onDispose(_persistenceService.dispose);

    final puzzleAsync = ref.watch(puzzleLoaderProvider);

    return puzzleAsync.when(
      data: (board) {
        // Detect puzzle change: if we had a previous puzzle and the ID changed,
        // clear all game state (selection, foundWords, lockedCells, etc.)
        final prevId = _lastLoadedPuzzleId;
        final newId = board.id;
        if (prevId != null && prevId != newId) {
          // IMPORTANT: Capture current state BEFORE clearing, so we can persist
          // the previous puzzle's progress (foundWords, lockedCells) correctly.
          final prevFoundWords = ref.read(foundWordsProvider).toList();
          final prevLockedCells =
              ref
                  .read(lockedCellsProvider)
                  .map((c) => '${c.row},${c.col}')
                  .toList();
          // Read the current grid from _previousGrid which we update on each
          // state change (see _schedulePersist)
          final prevGrid = _previousGrid;

          // Now clear all game state for the new puzzle
          _clearGameStateOnPuzzleChange(board);

          // Persist the previous puzzle's state asynchronously
          if (prevGrid != null) {
            final isCompleted =
                board.entries != null &&
                prevFoundWords.length == board.entries!.length;
            _persistPreviousPuzzle(
              prevId,
              prevGrid,
              prevFoundWords,
              prevLockedCells,
              isCompleted: isCompleted,
            );
          }
        }
        _lastLoadedPuzzleId = newId;
        // Initialize _previousGrid when loading a new board
        _previousGrid = board.grid.map(List<String?>.from).toList();
        return board;
      },
      loading: _handleLoading,
      error: _handleError,
    );
  }

  /// Handle loading state - returns dummy/empty board if no puzzle selected.
  GameBoard _handleLoading() {
    final selected = ref.read(selectedPuzzleIdProvider);
    if (selected == null) {
      // Return a dummy empty board to prevent UI crashes in tests or initial states
      return GameBoard(
        id: 'empty',
        title: '',
        gridSize: 0,
        createdAt: DateTime.now(),
        grid: [],
        clues: {},
        blackCells: [],
        difficulty: 1,
        language: 'en',
      );
    }
    throw StateError('Puzzle is loading: $selected');
  }

  /// Handle error state - throws with details.
  Never _handleError(Object e, StackTrace st) {
    final selected = ref.read(selectedPuzzleIdProvider) ?? '<null>';
    throw StateError('Failed to load puzzle id="$selected": $e');
  }

  /// Called when puzzle changes - clears selection, foundWords, lockedCells, etc.
  void _clearGameStateOnPuzzleChange(GameBoard newBoard) {
    // Also clear restored ID when switching
    _lastRestoredId = null;

    // Clear selection from previous puzzle
    try {
      ref.read(selectedCellProvider.notifier).select(null);
    } on Object {
      // ignore
    }
    // Clear foundWords from previous puzzle
    try {
      ref.read(foundWordsProvider.notifier).setFoundWords(<String>{});
    } on Object {
      // ignore
    }
    // Clear lockedCells from previous puzzle
    try {
      ref.read(lockedCellsProvider.notifier).setLockedCells(<CellKey>{});
    } on Object {
      // ignore
    }
    // Clear flashing cells
    try {
      ref.read(flashingCellsProvider.notifier).setFlashingCells(<CellKey>{});
    } on Object {
      // ignore
    }
    try {
      ref
          .read(flashingClearedCellsProvider.notifier)
          .setFlashingClearedCells(<CellKey>{});
    } on Object {
      // ignore
    }
  }

  /// Persist the previous puzzle's state asynchronously.
  /// This is called from build() BEFORE clearing state, so the values
  /// are captured correctly.
  void _persistPreviousPuzzle(
    String puzzleId,
    List<List<String?>> grid,
    List<String> foundWords,
    List<String> lockedCells, {
    required bool isCompleted,
  }) {
    _persistenceService.persistPreviousPuzzle(
      puzzleId: puzzleId,
      grid: grid,
      foundWords: foundWords,
      lockedCells: lockedCells,
      isCompleted: isCompleted,
    );
  }

  void _onPuzzleLoaderChanged(
    AsyncValue<GameBoard>? prev,
    AsyncValue<GameBoard> next,
  ) {
    if (!ref.mounted) {
      return;
    }
    if (next is! AsyncData<GameBoard>) {
      return;
    }

    final puzzleId = next.value.id;
    if (puzzleId == _lastRestoredId) {
      return;
    }
    _lastRestoredId = puzzleId;

    _restoreProgress(puzzleId, next.value);
  }

  Future<void> _restoreProgress(String puzzleId, GameBoard board) async {
    try {
      final success = await _progressService.loadProgress(
        board: board,
        setGrid: (grid) => state = state.copyWith(grid: grid),
        setFoundWords: (found) {
          ref.read(foundWordsProvider.notifier).setFoundWords(found);
          _triggerEndGameIfSolved(playVictorySound: false);
        },
        setLockedCells: (locked) {
          ref.read(lockedCellsProvider.notifier).setLockedCells(locked);
        },
        setElapsedSeconds: (seconds) {
          unawaited(ref.read(gameTimerProvider(board.id)).setElapsed(seconds));
        },
      );

      if (!success && ref.mounted) {
        _populateInitialFoundLockedFromGrid(board);
      }
    } on Object {
      if (ref.mounted) {
        _populateInitialFoundLockedFromGrid(board);
      }
    }
  }

  /// Populate initial found/locked sets based on current grid state.
  /// Called only when there's no stored progress to restore.
  void _populateInitialFoundLockedFromGrid(GameBoard board) {
    if (!ref.mounted) {
      return;
    }
    final entries = board.entries;
    if (entries != null && entries.isNotEmpty) {
      try {
        final result = _progressService.computeInitialState(board: board);
        if (!result.isEmpty) {
          ref
              .read(foundWordsProvider.notifier)
              .setFoundWords(result.foundWords);
          ref
              .read(lockedCellsProvider.notifier)
              .setLockedCells(result.lockedCells);
          _triggerEndGameIfSolved(playVictorySound: false);
        }
      } on Object catch (e, stack) {
        if (kDebugMode) {
          debugPrint('Error updating found/locked words: $e\n$stack');
        }
      }
    }
  }

  void setLetter(int row, int col, String? letter) {
    if (state.blackCells.isDisabled(row, col)) {
      return;
    }
    final normalizedLetter =
        letter == null || letter.isEmpty
            ? null
            : letter.substring(0, 1).toUpperCase();
    if (state.grid[row][col] == normalizedLetter) {
      return;
    }
    final newGrid = List<List<String?>>.of(state.grid);
    final rowCopy = List<String?>.of(newGrid[row]);
    rowCopy[col] = normalizedLetter;
    newGrid[row] = rowCopy;
    state = state.copyWith(grid: newGrid);
    _schedulePersist();
    // Check end-game in case foundWords were updated elsewhere synchronously
    try {
      _triggerEndGameIfSolved();
    } on Object {
      // ignore
    }
  }

  void toggleBlackCell(int row, int col) {
    final newGrid = List<List<String?>>.from(
      state.grid.map(List<String?>.from),
    );
    final newBlack = List<List<bool>>.from(
      state.blackCells.map(List<bool>.from),
    );
    newBlack[row][col] = !newBlack[row][col];
    if (newBlack[row][col]) {
      newGrid[row][col] = null;
    }
    state = GameBoard(
      id: state.id,
      title: state.title,
      gridSize: state.gridSize,
      createdAt: state.createdAt,
      grid: newGrid,
      clues: state.clues,
      blackCells: newBlack,
      difficulty: state.difficulty,
      entries: state.entries,
      solutionGrid: state.solutionGrid,
    );
    _schedulePersist();
  }

  // Deprecated public property accessors removed in favor of explicit API.
  // Use `setBoard(GameBoard)` to update the board and read the provider
  // state via `ref.watch(gameBoardProvider)` or `container.read(gameBoardProvider)`.

  void clearIncorrectLetters() {
    final cleaner = ref.read(incorrectLetterCleanerProvider);
    final result = cleaner.cleanWithResult(state);
    state = result.board;

    _schedulePersist();

    if (result.clearedCells.isNotEmpty) {
      ref
          .read(flashingClearedCellsProvider.notifier)
          .setFlashingClearedCells(result.clearedCells.toSet());
      final delay = ref.read(flashClearDelayProvider);
      if (delay == Duration.zero) {
        unawaited(
          Future.microtask(() {
            try {
              ref
                  .read(flashingClearedCellsProvider.notifier)
                  .setFlashingClearedCells(<CellKey>{});
            } on Object catch (e, st) {
              developer.log(
                'Clearing flashing cleared cells failed',
                error: e,
                stackTrace: st,
              );
            }
          }),
        );
      } else {
        Future.delayed(delay, () {
          try {
            ref
                .read(flashingClearedCellsProvider.notifier)
                .setFlashingClearedCells(<CellKey>{});
          } on Object catch (e, st) {
            developer.log(
              'Clearing flashing cleared cells failed',
              error: e,
              stackTrace: st,
            );
          }
        });
      }
    }
  }

  /// Reveal the solution letter at the given cell (if available).
  void revealLetterAt(int row, int col) {
    if (state.grid[row][col] != null) {
      return;
    }

    final letter = _revealService.revealLetterAt(
      board: state,
      row: row,
      col: col,
    );

    if (letter == null) {
      return;
    }

    state = state.updateCell(row, col, letter);

    // Play reveal sound
    if (!ref.read(gameAudioMutedProvider)) {
      unawaited(ref.read(gameAudioServiceProvider).playReveal());
    }
    _checkWordCompletionAfterReveal(CellKey(row, col));
    _schedulePersist();
  }

  /// Helper to check for word completion after a single cell reveal.
  void _checkWordCompletionAfterReveal(CellKey pos) {
    try {
      final result = _progressService.checkCompletionAtPos(
        board: state,
        pos: pos,
        currentFoundWords: ref.read(foundWordsProvider),
      );

      if (result.hasChanges) {
        final newFound = Set<String>.from(ref.read(foundWordsProvider))
          ..addAll(result.newlyFoundWords);
        final newLocked = Set<CellKey>.from(ref.read(lockedCellsProvider))
          ..addAll(result.cellsToFlash);

        ref.read(foundWordsProvider.notifier).setFoundWords(newFound);
        ref.read(lockedCellsProvider.notifier).setLockedCells(newLocked);

        _revealService.triggerFlash(
          cells: result.cellsToFlash,
          setFlashingCells:
              (v) =>
                  ref.read(flashingCellsProvider.notifier).setFlashingCells(v),
          getFlashDelay: () => ref.read(flashClearDelayProvider),
          playSuccess: () => ref.read(gameAudioServiceProvider).playSuccess(),
          shouldPlaySound: () => !ref.read(gameAudioMutedProvider),
        );
        _triggerEndGameIfSolved();
      }
    } on Object {
      // ignore
    }
  }

  /// Reveal the full entry (word) for the given PuzzleEntryData.
  void revealEntry(PuzzleEntryData entry) {
    final result = _revealService.revealEntry(
      board: state,
      entry: entry,
      currentFoundWords: ref.read(foundWordsProvider),
      currentLockedCells: ref.read(lockedCellsProvider),
    );

    if (!result.hasChanges) {
      return;
    }

    state = state.copyWith(grid: result.newGrid);
    ref.read(foundWordsProvider.notifier).setFoundWords(result.newFoundWords);
    ref
        .read(lockedCellsProvider.notifier)
        .setLockedCells(result.newLockedCells);
    _schedulePersist();

    _revealService.triggerFlash(
      cells: result.cellsToFlash,
      setFlashingCells:
          (v) => ref.read(flashingCellsProvider.notifier).setFlashingCells(v),
      getFlashDelay: () => ref.read(flashClearDelayProvider),
      playSuccess: () => ref.read(gameAudioServiceProvider).playSuccess(),
      shouldPlaySound: () => !ref.read(gameAudioMutedProvider),
    );

    _triggerEndGameIfSolved();
  }

  /// Reveal the entire puzzle (fill all non-black cells from the solution grid).
  void revealAll() {
    final sol = state.solutionGrid;
    if (sol == null) {
      return;
    }

    // Early return if puzzle is already fully revealed
    // Check if all entries are already marked as found
    final entries = state.entries;
    if (entries != null && entries.isNotEmpty) {
      final foundCount = ref.read(foundWordsProvider).length;
      if (foundCount == entries.length) {
        // Puzzle is already complete, nothing to reveal
        return;
      }
    }

    final result = _revealService.revealAll(
      board: state,
      currentFoundWords: ref.read(foundWordsProvider),
      currentLockedCells: ref.read(lockedCellsProvider),
      currentlyFlashing: ref.read(flashingCellsProvider),
    );

    state = state.copyWith(grid: result.newGrid);
    ref.read(foundWordsProvider.notifier).setFoundWords(result.newFoundWords);
    ref
        .read(lockedCellsProvider.notifier)
        .setLockedCells(result.newLockedCells);
    _schedulePersist();

    if (result.hasChanges) {
      _revealService.triggerFlash(
        cells: result.cellsToFlash,
        setFlashingCells:
            (v) => ref.read(flashingCellsProvider.notifier).setFlashingCells(v),
        getFlashDelay: () => ref.read(flashClearDelayProvider),
        playSuccess: () => ref.read(gameAudioServiceProvider).playSuccess(),
        shouldPlaySound: () => !ref.read(gameAudioMutedProvider),
      );
    }

    // After revealAll, check end-game once.
    try {
      _triggerEndGameIfSolved();
    } on Object {
      // ignore
    }
  }

  void _schedulePersist() {
    try {
      _previousGrid = state.grid.map(List<String?>.from).toList();
    } on Object {
      // ignore if state not ready
    }
    final entries = state.entries;
    final isCompleted =
        entries != null &&
        ref.read(foundWordsProvider).length == entries.length;

    _persistenceService.schedulePersist(
      puzzleId: state.id,
      grid: state.grid,
      foundWords: ref.read(foundWordsProvider),
      lockedCells: ref.read(lockedCellsProvider),
      elapsedSeconds: ref.read(gameTimerProvider(state.id)).elapsedSeconds,
      isCompleted: isCompleted,
    );
  }

  /// Reset the puzzle to its initial state (clear all user progress).
  void resetPuzzle() {
    // Clear the grid
    final newGrid = List<List<String?>>.generate(
      state.grid.length,
      (r) => List<String?>.generate(
        state.grid[r].length,
        (c) => state.blackCells.isDisabled(r, c) ? null : null,
      ),
    );
    state = state.copyWith(grid: newGrid);

    // Clear all game state
    ref.read(foundWordsProvider.notifier).setFoundWords(<String>{});
    ref.read(lockedCellsProvider.notifier).setLockedCells(<CellKey>{});
    // After a reset we deliberately clear selection so UI doesn't retain
    // focus on previously-selected cells from the prior game state.
    try {
      ref.read(selectedCellProvider.notifier).select(null);
    } on Object {
      // ignore
    }
    ref.read(flashingCellsProvider.notifier).setFlashingCells(<CellKey>{});
    ref
        .read(flashingClearedCellsProvider.notifier)
        .setFlashingClearedCells(<CellKey>{});

    // Reset timer
    try {
      ref.read(gameTimerProvider(state.id)).clear();
    } on Object {
      // ignore
    }

    // Clear persistence
    _schedulePersist();
  }

  /// Centralized end-game check: finalize timer and play victory when all
  /// entries are found. Call this from any code path that may complete the
  /// puzzle (typing, reveal actions, etc.). This uses `foundWordsProvider`
  /// which is the authoritative source of found entries.
  ///
  /// [playVictorySound]: If true, plays the victory sound. Set to false when
  /// loading an already-completed puzzle to avoid playing the sound.
  void _triggerEndGameIfSolved({bool playVictorySound = true}) {
    final solved = _endgameService.checkAndTriggerEndGame(
      board: state,
      foundWords: ref.read(foundWordsProvider),
      lastLoadedPuzzleId: _lastLoadedPuzzleId,
      timer: ref.read(gameTimerProvider(state.id)),
      persistenceService: _persistenceService,
      lockedCells: ref.read(lockedCellsProvider),
      isMuted: ref.read(gameAudioMutedProvider),
      audioService: ref.read(gameAudioServiceProvider),
      playVictorySound: playVictorySound,
    );

    if (solved) {
      // Any additional local cleanup if needed
    }
  }
}
