// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        // NOTE: Configure Firebase for iOS
        // 1. Create an iOS app in Firebase Console.
        // 2. Download GoogleService-Info.plist.
        // 3. Add options here (apiKey, appId, messagingSenderId, projectId, iosBundleId).
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    // NOTE: Production Security
    // When releasing to Play Store, Google will sign your app with a distinct certificate.
    // > Go to Play Console > Release > Setup > App Integrity > App Signing.
    // > Copy the SHA-1 certificate fingerprint.
    // > Add this SHA-1 to your Firebase Console > Project Settings > Android App.
    // > Updates restrictions in Google Cloud Console if needed.
    apiKey: 'AIzaSyCeZvScxCwFhaEgs2d533Jg7Irk41qRGAM',
    appId: '1:439585026140:android:c9865b7803057edf997699',
    messagingSenderId: '439585026140',
    projectId: 'croiz-1212d',
    storageBucket: 'croiz-1212d.firebasestorage.app',
  );
}
