spring:
  application:
    name: croiz-api
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/croiz
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    com.croiz: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
