import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:croiz/routes/app_router.dart';
import 'package:flutter/services.dart';
import 'package:croiz/features/splash/splash_screen.dart';
import 'package:croiz/core/config/app_languages.dart';
import 'package:croiz/core/theme.dart';
import 'package:croiz/services/providers.dart';
import 'package:croiz/services/persistence/hive_puzzle_storage.dart';
import 'package:croiz/features/game/providers/puzzle_loader_provider.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:croiz/l10n/app_localizations.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:sizer/sizer.dart';

import 'package:firebase_core/firebase_core.dart';
// Note: This file will be generated by `flutterfire configure`
import 'package:croiz/core/config/firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);

  // Initialize Firebase
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } on Object catch (e) {
    debugPrint('Firebase initialization failed: $e');
    // Continue running app even if Firebase fails,
    // though Gemini features won't work.
  }

  // Initialize Hive for puzzle persistence and open box.
  await HivePuzzleStorage.init();
  await HivePuzzleStorage.openBox();

  runApp(const ProviderScope(child: CroizApp()));
}

class CroizApp extends ConsumerStatefulWidget {
  const CroizApp({super.key});

  @override
  ConsumerState<CroizApp> createState() => _CroizAppState();
}

class _CroizAppState extends ConsumerState<CroizApp> {
  bool _initialized = false;

  // Called by the SplashScreen when core initialization completes.
  // Load persisted locale here so the app starts with the user's choice.
  Future<void> _onInitialized() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final saved = prefs.getString('locale');
      if (saved != null && saved.isNotEmpty) {
        ref.read(localeProvider.notifier).setLocale(Locale(saved));
      }

      // Load persisted UI preferences
      final isDark = prefs.getBool('pref_is_dark');
      if (isDark != null) {
        ref.read(appIsDarkProvider.notifier).setIsDark(isDark: isDark);
      }

      final azerty = prefs.getBool('pref_keyboard_azerty');
      if (azerty != null) {
        ref
            .read(gameKeyboardLayoutProvider.notifier)
            .setIsAzerty(isAzerty: azerty);
      }

      final ksize = prefs.getString('pref_keyboard_size');
      if (ksize != null && ksize.isNotEmpty) {
        try {
          final val = KeyboardSize.values.firstWhere((e) => e.name == ksize);
          ref.read(gameKeyboardSizeProvider.notifier).setSize(val);
        } on Object {
          // ignore if invalid
        }
      }

      final muted = prefs.getBool('pref_audio_muted');
      if (muted != null) {
        ref.read(gameAudioMutedProvider.notifier).setMuted(muted: muted);
      }

      // Optionally restore last selected puzzle so progress restoration runs.
      final lastSelected = prefs.getString('last_selected_puzzle');
      if (lastSelected != null && lastSelected.isNotEmpty) {
        ref.read(selectedPuzzleIdProvider.notifier).setSelected(lastSelected);
      }
    } on Exception catch (_) {
      // ignore and continue with default locale
    }

    if (mounted) {
      setState(() => _initialized = true);
    }
  }

  // Use centralized app themes from `AppTheme` to ensure consistency.
  static final _lightTheme = AppTheme.lightTheme();
  static final _darkTheme = AppTheme.darkTheme();

  @override
  Widget build(BuildContext context) {
    final isDark = ref.watch(appIsDarkProvider);
    final locale = ref.watch(localeProvider);

    if (!_initialized) {
      return Sizer(
        builder:
            (context, orientation, screenType) => MaterialApp(
              title: 'Croiz',
              theme: _darkTheme,
              darkTheme: _darkTheme,
              themeMode: ThemeMode.dark,
              debugShowCheckedModeBanner: false,
              home: SplashScreen(onInitialized: _onInitialized),
              localizationsDelegates: const [
                AppLocalizations.delegate,
                GlobalMaterialLocalizations.delegate,
                GlobalWidgetsLocalizations.delegate,
                GlobalCupertinoLocalizations.delegate,
              ],
              supportedLocales: AppLanguages.uiLocales,
            ),
      );
    }

    return Sizer(
      builder:
          (context, orientation, screenType) => MaterialApp.router(
            title: 'Croiz',
            theme: _lightTheme,
            darkTheme: _darkTheme,
            themeMode: isDark ? ThemeMode.dark : ThemeMode.light,
            routerConfig: appRouter,
            debugShowCheckedModeBanner: false,
            locale: locale,
            localizationsDelegates: const [
              AppLocalizations.delegate,
              GlobalMaterialLocalizations.delegate,
              GlobalWidgetsLocalizations.delegate,
              GlobalCupertinoLocalizations.delegate,
            ],
            supportedLocales: AppLanguages.uiLocales,
          ),
    );
  }
}
